project:
  type: website

website:
  title: "LearnWithMe"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/himmannshu
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: solar
    css: styles.css
execute:
  freeze: auto


