---
title: "LeetCode Problem Solving Tracker"
author: "Himanshu"
date: "2024-10-14"
---

# LeetCode Problem Solving Tracker

Below is a list of problems I'm working on:

## Problem List

### 1. [Bus Routes (40 times)](https://leetcode.com/problems/bus-routes/)
- [ ] Solved
- **Notes:** 
  *Write a brief note about the problem here...*

---

### 2. [Find the Closest Palindrome (19 times)](https://leetcode.com/problems/find-the-closest-palindrome/)
- [ ] Solved
- **Notes:** 
  *Write a brief note about the problem here...*

---

### 3. [Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit (15 times)](https://leetcode.com/problems/longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit/)
- [ ] Solved
- **Notes:** 
  *Write a brief note about the problem here...*

---

### 4. [Leftmost Column with at Least a One (15 times)](https://leetcode.com/problems/leftmost-column-with-at-least-a-one/)
- [ ] Solved
- **Notes:** 
  *Write a brief note about the problem here...*

---

### 5. [Merge Intervals (13 times)](https://leetcode.com/problems/merge-intervals/)
- [ ] Solved
- **Notes:** 
  *Write a brief note about the problem here...*

---

### 6. [Kth Smallest Element in a BST (12 times)](https://leetcode.com/problems/kth-smallest-element-in-a-bst/)
- [ ] Solved
- **Notes:** 
  *Write a brief note about the problem here...*

---

### 7. [Number of Islands (12 times)](https://leetcode.com/problems/number-of-islands/)
- [ ] Solved
- **Notes:** 
  *Write a brief note about the problem here...*

---

### 8. [Word Search II (12 times)](https://leetcode.com/problems/word-search-ii/)
- [ ] Solved
- **Notes:** 
  *Write a brief note about the problem here...*

---

### 9. [Evaluate Division (12 times)](https://leetcode.com/problems/evaluate-division/)
- [ ] Solved
- **Notes:** 
  *Write a brief note about the problem here...*

---

### 10. [Word Search (11 times)](https://leetcode.com/problems/word-search/)
- [ ] Solved
- **Notes:** 
  *Write a brief note about the problem here...*

---

### 11. [Construct Quad Tree (10 times)](https://leetcode.com/problems/construct-quad-tree/)
- [ ] Solved
- **Notes:** 
  *Write a brief note about the problem here...*

---

### 12. [Longest Repeating Character Replacement (10 times)](https://leetcode.com/problems/longest-repeating-character-replacement/)
- [ ] Solved
- **Notes:** 
  *Write a brief note about the problem here...*

---

### 13. [Top K Frequent Words (10 times)](https://leetcode.com/problems/top-k-frequent-words/)
- [ ] Solved
- **Notes:** 
  *Write a brief note about the problem here...*

---

### 14. [Two Sum (9 times)](https://leetcode.com/problems/two-sum/)
- [ ] Solved
- **Notes:** 
  *Write a brief note about the problem here...*

---

### 15. [Insert Delete GetRandom O(1) (8 times)](https://leetcode.com/problems/insert-delete-getrandom-o1/)
- [ ] Solved
- **Notes:** 
  *Write a brief note about the problem here...*

---

... *(Continue similarly for the rest of the problems)*
